---
apiVersion: v1
kind: Secret
metadata:
  namespace: gb
  name: redmine-secret-env
  labels:
    app.gb: redmine
data:
  REDMINE_SECRET_KEY_BASE: c3VwZXJzZWNyZXRrZXkK
  REDMINE_DB_PASSWORD: dGVzdHBhc3N3b3Jk
