apiVersion: v1
kind: Service
metadata:
  namespace: gb
  name: redmine
  labels:
    app.gb: redmine
spec:
  #type: NodePort
  #type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.gb: redmine

