apiVersion: v1
kind: Service
metadata:
  namespace: gb
  name: database
  labels:
    app.gb: psql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  # Pod to route service traffic  
  selector:
    app.gb: psql

