apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db1-pgsql-gb-10gi
  labels:
    type: local
    app.db: db1-pgsql-gb
spec:
  storageClassName: csi-ceph-hdd-gz1-retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  # Specify the path to persistent the volumes  
  hostPath:
    path: "/data/db"